server:
  port: 8999

eureka:
  instance:
    hostname: localhost  

spring:
  application:
    name: Gateway_API_Service
    
  cloud:
    gateway:
      routes:

        - id: DamagedProducts-service
          uri: lb://DamagedProducts-service
          predicates:
            - Path=/RPM/**